"""empty message

Revision ID: 6a14cdf98cf2
Revises: 6b8399876bd7
Create Date: 2019-09-26 10:06:58.977974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a14cdf98cf2'
down_revision = '6b8399876bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_snippet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_snippet')),
    sa.UniqueConstraint('title', name=op.f('uq_blog_snippet_title'))
    )
    op.create_table('blog_snippet_tag',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('snippet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['snippet_id'], ['blog_snippet.id'], name=op.f('fk_blog_snippet_tag_snippet_id_blog_snippet')),
    sa.ForeignKeyConstraint(['tag_id'], ['blog_tag.id'], name=op.f('fk_blog_snippet_tag_tag_id_blog_tag'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_snippet_tag')
    op.drop_table('blog_snippet')
    # ### end Alembic commands ###
