"""empty message

Revision ID: 800de69f1be1
Revises: 0ee50e9bf9b0
Create Date: 2019-09-22 15:27:23.827952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800de69f1be1'
down_revision = '0ee50e9bf9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_user', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=180),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_user', 'password',
               existing_type=sa.String(length=180),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
