"""empty message

Revision ID: f5c3508767b9
Revises: 800de69f1be1
Create Date: 2019-09-23 12:12:58.334466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5c3508767b9'
down_revision = '800de69f1be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_blog_tag_name'), 'blog_tag', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_blog_tag_name'), 'blog_tag', type_='unique')
    # ### end Alembic commands ###
