"""empty message

Revision ID: 0ee50e9bf9b0
Revises: afc2914ddf03
Create Date: 2019-09-21 16:41:48.365175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee50e9bf9b0'
down_revision = 'afc2914ddf03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_tag'))
    )
    op.create_table('blog_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['blog_user.id'], name=op.f('fk_blog_article_author_id_blog_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_article')),
    sa.UniqueConstraint('title', name=op.f('uq_blog_article_title'))
    )
    op.create_table('blog_article_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['blog_article.id'], name=op.f('fk_blog_article_likes_article_id_blog_article')),
    sa.ForeignKeyConstraint(['user_id'], ['blog_user.id'], name=op.f('fk_blog_article_likes_user_id_blog_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_article_likes'))
    )
    op.create_table('blog_article_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['blog_article.id'], name=op.f('fk_blog_article_tags_article_id_blog_article')),
    sa.ForeignKeyConstraint(['tag_id'], ['blog_tag.id'], name=op.f('fk_blog_article_tags_tag_id_blog_tag')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_article_tags'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_article_tags')
    op.drop_table('blog_article_likes')
    op.drop_table('blog_article')
    op.drop_table('blog_tag')
    # ### end Alembic commands ###
