"""empty message

Revision ID: afc2914ddf03
Revises: d7f4ee177b03
Create Date: 2019-09-20 11:02:28.735014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc2914ddf03'
down_revision = 'd7f4ee177b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_user', sa.Column('avatar_name', sa.String(), nullable=True))
    op.drop_column('blog_user', 'avatar_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_user', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('blog_user', 'avatar_name')
    # ### end Alembic commands ###
